# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LKBS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LKBS

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SnapKit' 
  pod 'HandyJSON'
  pod 'ObjectMapper'


  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'pop'
  pod 'UITableView+FDTemplateLayoutCell'

end
